In [51]:
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd


In [60]:
indexs = np.array([float(i) for i in range(0,40)], ndmin = 2)
print(indexs)
distmat =  indexs.transpose() * indexs
for i in range(indexs.shape[1]):
   # print(i)
    aa = np.exp(-(np.abs(indexs[0,:]-indexs[0,i]))/100)
   # print (aa)
    distmat[i,:] = aa
print(distmat)

change_means  = np.array([float(1) for i in range(0,40)], ndmin = 1)
#cov_change = 

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
  36. 37. 38. 39.]]
[[1.         0.99004983 0.98019867 ... 0.69073433 0.68386141 0.67705687]
 [0.99004983 1.         0.99004983 ... 0.69767633 0.69073433 0.68386141]
 [0.98019867 0.99004983 1.         ... 0.70468809 0.69767633 0.69073433]
 ...
 [0.69073433 0.69767633 0.70468809 ... 1.         0.99004983 0.98019867]
 [0.68386141 0.69073433 0.69767633 ... 0.99004983 1.         0.99004983]
 [0.67705687 0.68386141 0.69073433 ... 0.98019867 0.99004983 1.        ]]


In [66]:
means = np.random.normal(loc = 100, scale =30, size = (10,1))
means

changes =  np.random.multivariate_normal(mean = change_means, cov= 0.2*distmat, size = (10)) #np.random.normal(loc = 1, scale= 0.2, size = (10, 40))

outputs = changes * means

In [67]:
changes.shape

(10, 40)

In [68]:
np.median(outputs.mean(axis = 0) /  means.mean())

1.3428094694735722

In [69]:
np.median(outputs.sum(axis = 0) /  means.sum())

1.3428094694735722

In [70]:
np.median((outputs/means).mean(axis = 0))

1.4085162050836944

In [71]:
np.quantile((outputs/means).mean(axis=0),q = (0.1,0.5,0.9))

array([1.37055619, 1.40851621, 1.42240282])

In [72]:
np.quantile(outputs.mean(axis = 0) /  means.mean(),q = (0.1,0.5,0.9))

array([1.30427132, 1.34280947, 1.37753346])